n_species: 19

input_files:
  # Main input for orthology features: UNI, CNV, ACN, DUP
  orthology_table: data/anophelinae_orthology.tsv
  ultrametric_species_tree: data/anophelinae_ultrametric_tree.pep

features:
  UNI:
    is_gene_level_feature: false
  DUP:
    is_gene_level_feature: false
  ACN:
    is_gene_level_feature: false
  CNV:
    is_gene_level_feature: false
  AGE:
    is_gene_level_feature: false
  # SYN:
  #   input: data/GFFs.tsv
  #   is_gene_level_feature: false
