# n_species: 19

#input_files:
  # Main input for orthology features: UNI, CNV, ACN, DUP
orthology_table: input/apoidea_orthology.txt

# user orhtogroup features: several user determined features merged into a single file
# Columns: orthogroup \t gene \t feat1 \t feat2 ...
user_orthogroup_features_file: input/apoidea_og_feats.tsv

# user gene features: several user determined features merged into a single file
# Columns: gene \t species \t orthogroup \t feat1 \t feat2 ...
user_gene_features_files: # YET TO IMPLEMENT

# Specie tree file
species_tree: input/trees_Apoidea_RO_ultrametric.pep

default_orthogroup_features:
  - UNI
  - DUP
  - ACN
  - CNV
  - AGE

default_gene_features:

# Additional features:
additional_orthogroup_features:
  # - OG_SYN # IF gff file present

additional_gene_features:
  # - GENE_SYN # IF gff file present

# Aggregate GFF file:
gff_file: # YET TO IMPLEMENT
