# OrthoDB orthology table:
# if directly coming from OrthoDB v10 or lower, a script will automatically format it.
# Ortherwise, respect the column format:
# orthogroup <\t> gene <\t> species
# Make sure that gene names are unique across species, in order to avoid potential downstream flaws.
# One way to make gene ids unique is to simply attach the species name to it.
orthology_table: input/arthropoda_odb10v1_OG2genes.tab

# File containing lists of genes for clustering.
# First column must contain set name, followed by all of its gene names separated
# by tab (or in separeted cells in an Excel file saved as txt)
gene_sets:  input/dmel_immune_subfamilies.csv

# Add species codes to generate specific evolutionary features files
focus_species_list:
  #- 7460
  #- 148810 # PROBLEM: because of some Bash handling opening of files, this only works for 1 species at a time.

focus_gene_list_files:
  #- input/hymenoptera/genelists.txt # ADD COLUMNS WITH OTHER LISTS

# user orhtogroup features: any file of user-defined orthogroup features
# Columns: orthogroup \t feat1 \t feat2 ...
user_orthogroup_features_files:
  - input/arthropoda_evolrates_odb10v1.tab

# user gene features: any file of user-defined gene features
# Columns: gene \t feat1 \t feat2 ...
# IF NOT ALREADY THE CASE: format 'gene' column so that it includes the species code,
# separated by ':'. E.g.:
# species_code:geneid
user_gene_features_files:
  #- input/hymenoptera/amell_hym_gene_features.txt


# Specie tree file
ultrametric_species_tree: input/arthropoda_rooted_time.tree

# CAFE5 Base_change.tab results
cafe_results: input/arthropoda_Base_asr.tre

# Aggregated GFF file:
gff_file: # YET TO IMPLEMENT

# Metrics from the default_orthogroup_features that will be included in the computation process
# Comment the ones you wish to not compute.
selected_orthogroup_features:
  - UNI
  - DUP
  - ACN
  - CNV
  - AGE
  - RUN
  - EXP
  - STA
  - CON

default_orthogroup_features:
  - UNI
  - DUP
  - ACN
  - CNV
  - AGE
  - RUN
  - EXP
  - STA
  - CON

selected_gene_features:
  - UNI
  - DUP
  - ACN
  - CNV
  - AGE
  - RUN
  - EXP
  - STA
  - CON

default_gene_features:
  - UNI
  - DUP
  - ACN
  - CNV
  - AGE
  - RUN
  - EXP
  - STA
  - CON
