# n_species: 19

#input_files:
  # Main input for orthology features: UNI, CNV, ACN, DUP
orthology_table: input/Anophelinae_OGs.txt

# user orhtogroup features: several user determined features merged into a single file
# Columns: orthogroup \t gene \t feat1 \t feat2 ...
user_orthogroup_features_files:
  - input/user_features.txt

# user gene features: several user determined features merged into a single file
# Columns: gene \t species \t orthogroup \t feat1 \t feat2 ...
user_gene_features_files: # YET TO IMPLEMENT

# Specie tree file
ultrametric_species_tree: input/Anophelinae_ultrametric_time_tree.pep

# Metrics from the default_orthogroup_features that will be included in the computation process
# Comment one to remove it.
included_orthogroup_features:
  - UNI
  - DUP
  - ACN
  - CNV
  - AGE
#
# included_gene_features:
#
#
default_orthogroup_features:
  - UNI
  - DUP
  - ACN
  - CNV
  - AGE


# default_orthogroup_features:
#   set_1: # needs orthology table
#     - UNI
#     - DUP
#     - ACN
#
#   set_2: # needs ACN feature
#     - CNV
#
#   set_3: # needs orthology table and
#     - AGE



# Additional features:
additional_orthogroup_features:
  # - OG_SYN # IF gff file present

additional_gene_features:
  # - GENE_SYN # IF gff file present

# Aggregate GFF file:
gff_file: # YET TO IMPLEMENT
