n_species: 19

input_files:
  # Main input for orthology features: UNI, CNV, ACN, DUP
  orthology_table: data/orthology_anophelinae.tsv

features:
  UNI:
    gene_feature: false
  DUP:
    gene_feature: false
  CNV:
    gene_feature: false
  ACN:
    gene_feature: false
  AGE:
    input:
      species_tree: data/species_tree.tsv
    gene_feature: false
  SYN:
    input: data/GFFs.tsv
    gene_feature: false
