n_species: 19

input_files:
  # Main input for orthology features: UNI, CNV, ACN, DUP
  orthology_table: data/orthology_anophelinae.tsv

features:
  UNI:
    is_gene_level_feature: false
  DUP:
    is_gene_level_feature: false
  ACN:
    is_gene_level_feature: false
  CNV:
    is_gene_level_feature: false
  AGE:
    input:
      species_tree: data/species_tree.tsv
    is_gene_level_feature: false
  # SYN:
  #   input: data/GFFs.tsv
  #   is_gene_level_feature: false
