# OrthoDB orthology table:
# if directly coming from OrthoDB10 or lower, a scrpit will automatically format it.
# Ortherwise, respect the column format:
# orthogroup <\t> gene <\t> species
# where gene must be a column with unique gene identifiers (if thats not the case,
# simply collate the species code to the gene id).
OrthoDB_orthology_table: input/hymenoptera/Hymenoptera_OGs.txt
OMA_orthology_table: # example, yet to include formatting script for OMA table

# user orhtogroup features: several user determined features merged into a single file
# Columns: orthogroup \t feat1 \t feat2 ...
user_orthogroup_features_files:
  - input/hymenoptera/Hymenoptera_OGs_EvolMetrics.tsv

# user gene features: several user determined features merged into a single file
# Columns: gene \t feat1 \t feat2 ...
user_gene_features_files:
  - input/hymenoptera/hymenoptera_gene_features.txt


# Specie tree file
ultrametric_species_tree: input/hymenoptera/Hymenoptera_RO_ultrametric.pep

# CAFE summary report
cafe_report:

# Aggregated GFF file:
gff_file: # YET TO IMPLEMENT

# Metrics from the default_orthogroup_features that will be included in the computation process
# Comment one to remove it.
selected_orthogroup_features:
  - UNI
  - DUP
  - ACN
  - CNV
  - AGE

selected_gene_features:


default_orthogroup_features:
  - UNI
  - DUP
  - ACN
  - CNV
  - AGE

default_gene_features:
  # - SYN



# default_orthogroup_features:
#   set_1: # needs orthology table
#     - UNI
#     - DUP
#     - ACN
#
#   set_2: # needs ACN feature
#     - CNV
#
#   set_3: # needs orthology table and
#     - AGE



## Additional features:
# additional_orthogroup_features:
  # - OG_SYN # IF gff file present

# additional_gene_features:
  # - GENE_SYN # IF gff file present
