n_species: 19

features:
  UNI:
    infiles:
      orthology_table: data/orthology_anophelinae.tsv
    gene_metric: false
  DUP:
    infiles:
      orthology_table: data/orthology_anophelinae.tsv
    gene_metric: false
  CNV:
    infiles:
      orthology_table: data/orthology_anophelinae.tsv
    gene_metric: false
  ACN:
    infiles:
      orthology_table: data/orthology_anophelinae.tsv
    gene_metric: false
  AGE:
    infiles:
      orthology_table: data/orthology_anophelinae.tsv
      species_tree: data/species_tree.tsv
    gene_metric: false
  SYN:
    infile: data/GFFs.tsv
    gene_metric: false
