configfile: 'config.yaml'

include: 'rules/utils.smk'

input_list = get_input()
# missing_input_files = get_missing_input_file_list(input_list)

USER_OG_FEATURES = input_list['user_orthogroup_features']
USER_GENE_FEATURES = input_list['user_gene_features']
OG_FEATURES_TO_COMPUTE = input_list['orthogroup_features_to_compute']
GENE_FEATURES_TO_COMPUTE = input_list['gene_features_to_compute']
FOCUS_SPECIES_LIST = input_list['focus_species_list']

include: 'rules/preprocess_input.smk'
include: 'rules/user_features.smk'
include: 'rules/compute_features.smk'
include: 'rules/merge_orthogroup_features.smk'
include: 'rules/merge_gene_features.smk'
include: 'rules/postprocess_features.smk'
include: 'rules/genesets_clusters.smk'


rule all:
    input:
        rules.merge_orthogroup_features.output,
        rules.merge_gene_features.output
        # rules.extract_focus_species_features.output,
        # rules.extract_gene_lists_features.output,
        # rules.get_orthogroup_sets_features.output,
        # rules.pvclust_on_sets.output,
        # rules.pca_on_sets.output,
        # rules.pairwise_comparisons_on_sets.output,
        # rules.tsne_on_sets.output
